// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQfCV1rtpttYQpFWEv4W2bK3jR60aZifU',
    appId: '1:758415269244:web:864d8aa3aa4c90c9e5d8f9',
    messagingSenderId: '758415269244',
    projectId: 'frutella-app',
    authDomain: 'frutella-app.firebaseapp.com',
    storageBucket: 'frutella-app.firebasestorage.app',
    measurementId: 'G-W4591ZDW01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfrRdW2Dx993eDBHnsZ77UjVWYf9JjGb0',
    appId: '1:758415269244:android:54310bc21ae4664ce5d8f9',
    messagingSenderId: '758415269244',
    projectId: 'frutella-app',
    storageBucket: 'frutella-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNwi_PWyOJtuysdc7Wd1l2HZG2yhajTVA',
    appId: '1:758415269244:ios:c3f066263fd91a57e5d8f9',
    messagingSenderId: '758415269244',
    projectId: 'frutella-app',
    storageBucket: 'frutella-app.firebasestorage.app',
    iosBundleId: 'com.example.sukaapp',
  );

}